services:
"  - type: web"
"    name: astrobot-api"
"    env: python"
"    plan: free"
"    pythonVersion: \"3.9.18\""
"    buildCommand: pip install -r requirements.txt"
"    startCommand: python main.py"
"    envVars:"
"      - key: BOT_TOKEN"
"        value: your_bot_token_here"
"      - key: GEMINI_API_KEY"
"        value: your_gemini_key_here"
"      - key: ADMIN_ID"
"        value: your_telegram_id_here"
